name: PyPi Release

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - run: sudo apt-get install gettext -y
    - run: python -m pip install --upgrade pip build wheel twine
    - run: python -m build --sdist --wheel
    - run: python -m twine upload dist/*
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
